version: '3'
services:
  postgres:
    image: 'postgres:14.6'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:6.2.10'
  nginx:
    depends_on:
      - api
      - react-app
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  react-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./fibbonaci-app
    volumes:
      - /app/node_modules
      - ./fibbonaci-app:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
